### ISSUE TITLE
aws-greengrass-labs-database-influxdb: Curly bracket missing in the policy document

### ISSUE THREAD

**Issue by SunithaE** [awslabs/aws-greengrass-labs-database-influxdb#6]
**Describe the bug**
Open curly bracket missing in the policy statement

**To Reproduce**
    {
    "Version": "2012-10-17",
    "Statement": [
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": [
                "<influxDB secret arn>"
            ]
        }
    ]
}

**Expected behavior**
    {
    "Version": "2012-10-17",
    "Statement": [
{
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": [
                "<influxDB secret arn>"
            ]
        }
    ]
}

**Actual behavior**
Open curly braces missing resulting in syntax error of the json policy document

**Environment**
 - OS: [e.g. Ubuntu 20.04] (If possible, provide output of `uname -a`)
 - JDK version:
 - Nucleus version:

**Additional context**

E.g. what is the impact of the bug? Unable to create policy which results in no interaction between the device and the secrets manager

**Comment by pallavi03** [comment]
Resolved with https://github.com/awslabs/aws-greengrass-labs-database-influxdb/pull/7
